### ISSUE TITLE
Add version of Twilio API to package

### ISSUE THREAD

**Issue by muthulee** [wso2-ballerina/package-twilio#4]

**Comment by ldclakmal** [comment]
@muthulee The current implementation of Twilio is supported by Twilio REST API version 2010-04-01. So shall I change my package name as **twilio20100401** ?

These are the Twilio docs used for current implementation.
[1] https://www.twilio.com/docs/iam/api
[2] https://www.twilio.com/docs/sms/send-messages
[3] https://www.twilio.com/docs/voice/make-calls

**Comment by ldclakmal** [comment]
But the following REST APIs of Twilio has the **v1**.
https://www.twilio.com/docs/voice/pricing

**Comment by muthulee** [comment]
Shall we call it v1?

**Comment by ldclakmal** [comment]
Okay. Then the package name would be **twilio1**.

Is that okay since different REST end points have different versions?
SMS API - `https://api.twilio.com/2010-04-01/`
Voice Call API - `https://api.twilio.com/2010-04-01/`
Accounts API - `https://api.twilio.com/2010-04-01/`
Pricing API - `https://pricing.twilio.com/v1/`

**Comment by muthulee** [comment]
For now let's keep it as twilio as it looks like the 1st version.
